# sonar-project.properties
sonar.organization=RonaldBorda
sonar.projectKey=0e018f3919efbe2751a83e2b6ba3ed6dab03cfea
sonar.host.url=https://sonarcloud.io

# Configuración para Java con archivos en la raíz
sonar.sources=.
sonar.java.binaries=build/classes
sonar.sourceEncoding=UTF-8

# Excluir archivos no relevantes (opcional)
sonar.exclusions=**/build/**, **/.github/**, **/sonar-project.properties
